spring.application.name=minilink

# Enalbe H2 Database in the memory
#spring.datasource.url=jdbc:h2:mem:minilinkdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

#  Spring Boot will automatically make the tables (update)
spring.jpa.hibernate.ddl-auto=update

# Enable the consoleso we can view it on the browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Gemini API KEY
gemini.api.key=API-KEY-HERE

# DATABASE
# ???? ??? Spring Boot ??? ????? ? ???? ??? ????? ????? ?? ???????
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/minilink_db
spring.datasource.username=minilink_user
spring.datasource.password=passcode

# ???? ??? Java ?? ??????? ???? ??????? ????????!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
